_target_: apep.model.template.MotionPlanningTransformerTargetParams
_convert_: 'all'
future_trajectory_sampling:
    _target_: apep.utils.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 8
    # time_horizon: 8.0
    interval_length: 1.0
