_target_: torch.optim.AdamW
_convert_: 'all'

lr: 1e-4  # learning rate
weight_decay: 0.01  # weight decay coefficient
betas: [0.9, 0.999]  # coefficients used for computing running averages of gradient and its square
